### ISSUE TITLE
Would it be possible to restrict access to a course based on language

### ISSUE THREAD

**Issue by peterhuppertz** [ewallah/moodle-availability_language#12]
We currently use the module to show/hide certain sections based on language, which works wonderful. However course titles using {mlang} can get too long for the field restriction. So I wonder if it would be possible to restrict a whole course to a certain language to circumvent that problem?

**Comment by ewallah** [comment]
Hello @peterhuppertz,

one can force one language to a course in the course settings:
course administration / Edit settings / Appearance / Force language.

When this setting is enabled, all users see the course in the forced language. But when the language is forced, this filter and probably the language filter stop working. There is no need to filter as the condition will always be true or false. A module that is always false should be deleted as it will never be shown to a student in a course with a forced language.

This plugin filters course content, you talk about restricting access to a course based on language.  Access or no access to a course is handled by an enrollment plugin.  In your case I would change my theme so users only can see the courses in their language.

R

**Comment by peterhuppertz** [comment]
Thank you for the comments. For now I changed the length of the course fullname field, which is not ideal since it is a change in the core. However, there's already a request for the change: https://tracker.moodle.org/browse/MDL-70556?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel
