### ISSUE TITLE
Install on moodle 4

### ISSUE THREAD

**Issue by danbuntu** [ewallah/moodle-availability_language#14]
Hello

I've trying to install this on moodle 4.0.4

I've tried to install the plugin both by Moosh and by uploading the zip file via the moodle web frontend.

When I then go to the plugins page the plugin is listed as 'to be installed'

However there is no 'upgrade database' option, likewise running 'upgrade.php' from the cli doesn't pick is up as needing to be installed.

As such the install doesn't complete.

**Comment by ewallah** [comment]
Which version of plugin - php - moodle - os are you using?
Did you remove all previous installations of this plugin?

**Comment by danbuntu** [comment]
After some more testing I found this to be an issue with our Moodle install and the plugin. 
We had a bunch of missing on disk plugins and these seemed to stop the upgrade script running correctly. After we had uninstalled them then plugins started to install as expected.
