### ISSUE TITLE
Support restriction also for other than the authenticated user

### ISSUE THREAD

**Issue by juho-jaakkola** [ewallah/moodle-availability_language#5]
I have a custom report that lists the activity completion status for each course participant. The course is multilingual, so there are multiple duplicates of each activity in different languages.

For each participant I need to list only those activities that are visible to them. To achieve this I am checking the availability of each activity for each user.

Let's say I have two users:
 - Donald Duck: Uses English as their preferred language
 - Homer Simpson: Uses Finnish as their preferred language

The desired result in the report:
```
Donald Duck: Exam 1A (English) - Completed
Homer Simpson: Tentti 1A (Finnish) - Not completed
```
The current result if UI language of the report viewer is English:
```
Donald Duck: Exam 1A (English) - Completed
Homer Simpson: Exam 1A (English) - Not completed
```
The current result if UI language of the report viewer is Finnish:
```
Donald Duck: Tentti 1A (Finnish) - Not completed
Homer Simpson: Tentti 1A (Finnish) - Not completed
```

This is caused by the fact that the plugin checks the language of the *logged in* user instead of the user whose access is should be checking.

The culprit is here: https://github.com/ewallah/moodle-availability_language/blob/master/classes/condition.php#L104

Instead of using `current_language()`, which defaults to the language of the logged in user, it should check the language of the user passed as the parameter.

**Comment by ewallah** [comment]
Great catch!

I always overruled the PHP mess detector warning in https://travis-ci.org/ewallah/moodle-availability_language/jobs/227411546 (96 VIOLATION Avoid unused parameters such as '$userid'), thinking that the parameter was indirectly used in the current_language() function. But you proved I should have given it three more thoughts...

The code you provide looks good, except I think there is an extra check needed:

     global $CFG, $DB, $USER;
     // If course has forced language.
     $course = $info->get_course();
     $allow = false;

     if (isset($course->lang) && $course->lang == $this->languageid) {
         $allow = true;
     }
     if ($userid == $USER->id) {
        // Checking the language of the currently logged in user, so do not
        // default to the account language, because the session language
        // or the language of the current course may be different.
        $language = current_language();
    } else {
        // Checking access for someone else than the logged in user, so
        // use the preferred language of that user account.
        $language = $DB->get_field('user', 'lang', ['id' => $userid]);
        if (empty($language)) {
             $language = isset($CFG->lang) ? $CFG->lang :  'en';
        }
    }

    if ($language == $this->languageid) {
         $allow = true;
     }

     if ($not) {
         $allow = !$allow;
     }
    ....

This weekend, I will try to test and integrate these changes.  Perhaps I should also have a look at the other violation warning: 96 VIOLATION Avoid unused parameters such as '$grabthelot'

**Comment by juho-jaakkola** [comment]
Ok, I will add the extra check. But can you first address my question in the comment https://github.com/ewallah/moodle-availability_language/pull/6#issuecomment-299437213

**Comment by ewallah** [comment]
Fixed in latest versions.
