### ISSUE TITLE
Remove .gitignore

### ISSUE THREAD

**Issue by T4m** [ewallah/moodle-availability_language#9]
Hi ewallah,
I had to fork your repo to keep away the .gitignore file, for these reasons:
- Main reason: our deployment process take in account the gitignore of submodules, then **yui/build** is not included, then nothing work
- *yui/build* is supposed to be ignored, but is versionned
- Seems that every other statements in the .gitignore are related to dev environments and should go to your global .gitignore.

My suggestion: remove the .gitignore file or empty it.

**Comment by ewallah** [comment]
Hi T4m,

Thanks for the problem report.

As far as I can see, the .gitignore file arrived in the repo upon some suggestions in my starting days on github.  I will remove the file ASAP.

**Comment by ewallah** [comment]
File removed.
